services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm start"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=dynamodb
      - DB_PORT=8000
      - FLASK_PORT=5000
      - AWS_REGION_NAME=us-west-2
      - AWS_ACCESS_KEY_ID=fakeAwsAccessKeyId
      - AWS_SECRET_ACCESS_KEY=fakeAwsSecretAccessKey
    ports:
      - '5000:5000'
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - dynamodb-data:/home/dynamodblocal/data

volumes:
  dynamodb-data: